#!/usr/bin/env python3
"""Bundle Lua modules into a single file for CC:Tweaked.

Usage example:
  python tools/bundle_cc_tweaked.py -s custom -o bundle.lua --minify

This writes a file that registers each module
as `package.preload["modname"] = function(...) ... end`.
If `luamin` is installed and `--minify` is passed,
it will be used to minify each file; otherwise files are concatenated raw.
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path


def minify_with_luamin(path: Path) -> str:
    try:
        # Try direct exec first; on some Windows setups the luamin shim may
        # require a shell.
        try:
            proc = subprocess.run(["luamin", "-f", str(path)],
                                  capture_output=True, text=True, check=False)
        except FileNotFoundError:
            proc = None
    except FileNotFoundError:
        return None
    # If direct exec failed or returned an error, try via the shell (works for
    # .cmd/.bat shims on Windows)
    if proc is None or proc.returncode != 0:
        try:
            cmd = f'luamin -f "{str(path)}"'
            proc2 = subprocess.run(cmd, shell=True, capture_output=True,
                                   text=True, check=False)
        except FileNotFoundError:
            return None
        if proc2.returncode != 0:
            return None
        return proc2.stdout
    return proc.stdout


def simple_safe_minify(src: str) -> str:
    # Very conservative: remove trailing spaces and empty lines only.
    # Avoid stripping comments or altering strings to stay safe for Lua code.
    lines = []
    for line in src.splitlines():
        i = line.rstrip()
        if i == "":
            continue
        lines.append(i)
    return "\n".join(lines) + "\n"


def module_name_from_path(src_dir: Path, file_path: Path) -> str:
    rel = file_path.relative_to(src_dir)
    parts = rel.with_suffix("").parts
    # join with '.' to create module-like name; also accept single names
    return ".".join(parts)


def read_file(path: Path, use_minify: bool = False) -> str:
    # Minification is intentionally applied only to the final assembled bundle,
    # not each module file individually.
    with path.open("r", encoding="utf-8") as f:
        return f.read()


def minify_final_bundle(path: Path) -> None:
    original = path.read_text(encoding="utf-8")
    tmp_path = path.with_suffix(path.suffix + ".luamin.tmp")
    tmp_path.write_text(original, encoding="utf-8")

    minified = minify_with_luamin(tmp_path)
    if minified is None:
        print(
            f"warning: 'luamin' not found or failed for {path},"
            " falling back to conservative minify",
            file=sys.stderr)
        minified = simple_safe_minify(original)

    path.write_text(minified, encoding="utf-8")
    tmp_path.unlink(missing_ok=True)
    print(f"Minified final bundle: {path}")


def find_lua_files(src_dir: Path, include_subdirs: bool):
    for root, dirs, files in os.walk(src_dir):
        for fn in files:
            if fn.lower().endswith(".lua"):
                yield Path(root) / fn
        if not include_subdirs:
            break


def write_bundle(modules, out_path: Path,
                 package_prefix: str = None, use_minify: bool = False):
    with out_path.open("w", encoding="utf-8") as f:
        f.write("-- Bundled Lua modules for CC:Tweaked\n")
        f.write("-- Generated by bundle_cc_tweaked.py\n\n")
        f.write("package = package or {}\n")
        f.write("package.preload = package.preload or {}\n\n")
        for name, code in modules:
            key = (package_prefix + name) if package_prefix else name
            f.write(f"package.preload[\"{key}\"] = function(...)\n")
            # indent module code by 4 spaces to keep readable
            for line in code.splitlines():
                f.write("    " + line + "\n")
            f.write("end\n\n")
    if use_minify:
        minify_final_bundle(out_path)
    print(f"Wrote bundle to: {out_path}")


def runtime_preload_text(
        modules, package_prefix: str = None, runtime: bool = False):
    # produce minimal preload-only content (no build helpers). If runtime
    # True, strip comments/extra lines.
    parts = []
    parts.append(f'local packagePrefix = "{package_prefix}"')
    parts.append("pluginAlwaysDownload = false")
    parts.append("pluginDownloadEnabled = true")
    parts.append(
        'local pluginRepoBase = "http://skeleti.asuscomm.com:8000/plugins/"')
    parts.append("local real_time = true")
    parts.append("package = package or {}")
    parts.append("package.preload = package.preload or {}")
    for name, code in modules:
        key = (package_prefix + name) if package_prefix else name
        # Keep module exactly as read, but ensure it's returned where
        # appropriate.
        buf = [f"package.preload[\"{key}\"] = function(...)"]
        for line in code.splitlines():
            buf.append("    " + line)
        buf.append("end")
        parts.append("\n".join(buf))

    out = "\n\n".join(parts) + "\n"
    if runtime:
        # very small squeeze: remove consecutive blank lines
        out = "\n".join([ln.rstrip()
                        for ln in out.splitlines() if ln.strip() != ""]) + "\n"
    return out


def write_runtime_preload(modules, out_path: Path, package_prefix: str = None,
                          runtime: bool = False, use_minify: bool = False):
    out = runtime_preload_text(modules, package_prefix, runtime)
    with out_path.open("w", encoding="utf-8") as f:
        f.write(out)
    if use_minify:
        minify_final_bundle(out_path)
    print(f"Wrote runtime preload to: {out_path}")


def embed_into_file(modules, out_path: Path, main_file: Path,
                    package_prefix: str = None, runtime: bool = False,
                    use_minify: bool = False):
    if not main_file.exists():
        raise FileNotFoundError(main_file)

    main_text = main_file.read_text(encoding="utf-8")
    preload_text = runtime_preload_text(modules, package_prefix, runtime)

    new_text = preload_text + "\n" + main_text
    out_path.write_text(new_text, encoding="utf-8")
    if use_minify:
        minify_final_bundle(out_path)
    print(f"Embedded main file into: {out_path}")


def main():
    p = argparse.ArgumentParser(
        description="Bundle Lua modules into a single file for CC:Tweaked")
    p.add_argument(
        "-s",
        "--src",
        default="custom",
        help="Source directory containing .lua modules")
    p.add_argument(
        "-o",
        "--out",
        default="bundle.lua",
        help="Output Lua bundle file")
    p.add_argument(
        "--minify",
        action="store_true",
        help="Minify the final generated Lua bundle with 'luamin'"
        "(falls back if not available)")
    p.add_argument(
        "--no-recursive",
        dest="recursive",
        action="store_false",
        help="Do not recurse into subdirectories")
    p.add_argument(
        "--prefix",
        default="",
        help="Optional prefix to prepend to module names"
        " in package.preload keys")
    p.add_argument(
        "--runtime",
        action="store_true",
        help="Produce minimal runtime preload-only bundle (no build helpers)")
    p.add_argument(
        "--embed",
        default=None,
        help="Embed the preload output into the specified"
        " init file (e.g. milstart.lua). A backup will be created.")
    args = p.parse_args()

    src_dir = Path(args.src).resolve()
    if not src_dir.exists() or not src_dir.is_dir():
        print(f"Source directory not found: {src_dir}", file=sys.stderr)
        sys.exit(2)

    files = list(find_lua_files(src_dir, args.recursive))
    if not files:
        print("No .lua files found in source directory", file=sys.stderr)
        sys.exit(0)

    modules = []
    for fp in sorted(files):
        name = module_name_from_path(src_dir, fp)
        code = read_file(fp, args.minify)
        modules.append((name, code))
        print(f"Added: {name} <- {fp}")

    out_path = Path(args.out).resolve()
    if args.embed:
        main_file = Path(args.embed).resolve()
        embed_into_file(
            modules,
            out_path,
            main_file,
            args.prefix,
            args.runtime,
            args.minify)
    else:
        if args.runtime:
            write_runtime_preload(
                modules,
                out_path,
                args.prefix,
                args.runtime,
                args.minify)
        else:
            write_bundle(modules, out_path, args.prefix, args.minify)


if __name__ == "__main__":
    main()
